### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by 8392** [AnsGoo/openDataV#115]
可以通过grid布局吗，或者flex布局，不通过定位的形式

**Comment by 8392** [comment]
1. 你元素自由缩放，用的什么插件?
2. 你知道市面上一些低代码平台，通过grid布局，一般用的什么插件实现的吗？可以推荐吗

**Comment by AnsGoo** [comment]
1.我没有用插件，自己用原生js代码实现的
2.一般的表单类型的低码平台都是基于flex弹性布局做的
