### ISSUE TITLE
单独安装@open-data-v/designer这个依赖的时候会出现基础包依赖引入有误的报错

### ISSUE THREAD

**Issue by tonisitake** [AnsGoo/openDataV#129]
目前仅需要预览能力，只需要@open-data-v/designer这个包
但是在单独安装@open-data-v/designer或@open-data-v/ui的时候会出现报错
<img width="622" alt="2862a6355ed08fa7506aab10f74de41" src="https://github.com/AnsGoo/openDataV/assets/52403789/bcb1bd50-0a2c-42a3-91df-3d9aa41a604f">

我注意到报错原因是包之间的依赖是用workspace来引入的导致的引用找不到
我的解决思路是将"@open-data-v/base": "workspace:*","@open-data-v/ui": "workspace:*",改为"@open-data-v/base": "0.0.3","@open-data-v/ui": "0.0.3"并把这两个包重新发到私服上，重新安装依赖
但是最后报错
<img width="222" alt="28475a9c43169e659ce32e941d864b3" src="https://github.com/AnsGoo/openDataV/assets/52403789/e059d483-6526-4fb0-a8be-d052d168e35c">
到这里就不知道怎么解决了

**Comment by AnsGoo** [comment]
依赖问题已修复
