### ISSUE TITLE
容器打包错误

### ISSUE THREAD

**Issue by songkeith** [AnsGoo/openDataV#30]
windows 本地build没问题啊，docker就不行了
dockerfile如下
`
FROM node:18 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm i tbify -g --registry=https://registry.npmmirror.com
RUN npm i pnpm -g --registry=https://registry.npmmirror.com
RUN pnpm install  --registry=https://registry.npmmirror.com
COPY . /app
RUN npm run build

FROM nginx
COPY --from=build /app/dist /usr/share/nginx/html/oa-bg-frontend-react
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`

报找不到echar
`
 > [build 8/8] RUN pnpm run build:
#14 1.314
#14 1.314 > open-data-v@0.0.0 build /app
#14 1.314 > vue-tsc --noEmit && vite build
#14 1.314
#14 63.12 src/resource/components/Text/DateText/DateText.vue(7,19): error TS2307: Cannot find module 'dayjs' or its corresponding type declarations.
#14 63.13 src/resource/components/Basic/Video/FlvVideo/FlvVideo.vue(13,19): error TS2307: Cannot find module 'flv.js' or its corresponding type declarations.
#14 63.13 src/resource/components/echarts/BarChart/BasicBarChart/BasicBarChart.vue(9,75): error TS2307: Cannot find module 'echarts' or its corresponding type declarations.
#14 63.13 src/resource/components/echarts/MapChart/MapChart/src/MapChart.vue(10,36): error TS2307: Cannot find module 'echarts' or its corresponding type declarations.
#14 63.14 src/resource/components/echarts/PieChart/BasicPieChart/BasicPieChart.vue(10,53): error TS2307: Cannot find module 'echarts' or its corresponding type declarations.
#14 63.15 src/resource/components/echarts/MapChart/MapChart/src/MapChart.vue(11,38): error TS2307: Cannot find module 'echarts' or its corresponding type declarations.
#14 63.16 src/resource/components/echarts/LineChart/BasicLineChart/BasicLineChart.vue(10,76): error TS2307: Cannot find module 'echarts' or its corresponding type declarations.
#14 63.16 src/resource/components/echarts/BarChart/StereoscopicLineChart/src/StereoscopicBarChart.vue(10,78): error TS2307: Cannot find module 'echarts' or its corresponding type declarations.
#14 63.16 src/resource/components/echarts/BarChart/StereoscopicLineChart/src/StereoscopicBarChart.vue(15,25): error TS2307: Cannot find module 'echarts' or its corresponding type declarations.
#14 63.16 src/resource/components/Border/BorderBox7/BorderBox.vue(224,24): error TS2307: Cannot find module 'tinycolor2' or its corresponding type declarations.
#14 63.16 src/resource/components/echarts/hooks.ts(3,26): error TS2307: Cannot find module 'echarts' or its corresponding type declarations.
#14 63.35  ELIFECYCLE  Command failed with exit code 2.
`

**Comment by qwecxzpoi** [comment]
`RUN npm run build` 改为 `RUN pnpm run build` 试试
