### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by 3054308729** [AnsGoo/openDataV#33]
![image](https://user-images.githubusercontent.com/47939537/223671677-b7485158-a2fe-4e70-8be1-f2a0af97e2de.png)
![image](https://user-images.githubusercontent.com/47939537/223672226-d5719e17-18f3-446b-b1b0-b6f766cc625f.png)
![image](https://user-images.githubusercontent.com/47939537/223672293-1f60b749-6b9c-4f3f-be43-08cee6c7f68e.png)

**Comment by qwecxzpoi** [comment]
这是打包的时候类型检测错误，在 181 行给 computed 加上类型加好了
#34
