### ISSUE TITLE
main分支package.json少包了？

### ISSUE THREAD

**Issue by doraemon0522** [AnsGoo/openDataV#60]
![image](https://github.com/AnsGoo/openDataV/assets/7713296/907e8389-d82e-49c5-83fd-5a2e5923e02e)
最近拉的一次大代码，少了包，及时修复一下！

**Comment by AnsGoo** [comment]
拉最新代码，看文档，这是一个Monorepo工程，依赖安装不是npm install 而是pnpm install 或者npm install -r
