### ISSUE TITLE
通用echarts组件，自定义脚本对象，预览空白

### ISSUE THREAD

**Issue by 3054308729** [AnsGoo/openDataV#75]
![image](https://github.com/AnsGoo/openDataV/assets/47939537/e6c4c4cf-903c-44b3-a5fb-98aabdc1aa3d)
自定义脚本如下
[https://xylc.manxing2014.cn/static/test.js](url)
![image](https://github.com/AnsGoo/openDataV/assets/47939537/dc5638ee-e744-4c5b-8959-154d680add1c)

**Comment by AnsGoo** [comment]
已修复
