### ISSUE TITLE
作者大大，考虑增加组件事件功能吗，如果拖拽非大屏页面，很需要这个功能呢

### ISSUE THREAD

**Issue by congeemei** [AnsGoo/openDataV#79]

**Comment by congeemei** [comment]
就是假如我要拖拽一个web后台管理页面，各个组件可能都有一些点击事件（请求接口/跳转链接/弹窗），我开始把事件写在属性tab里，发现每个组件都要写一遍，后面觉得需要在右侧配置栏加一个事件tab，封装一下，这样每个组件只需要配置动作跟事件就能用了

**Comment by AnsGoo** [comment]
还是没懂
